services:
  backend:
    build: ./backend
    container_name: url-shortener
    ports:
      - "8000:8000"
    env_file:
      - ./backend/nev
    depends_on:
      - db
      - redis
  
  db:
    image: postgres:18.1
    container_name: url-shortener-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: url_shortener_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8.6
    container_name: url-shortener-redis
    ports:
      - "6379:6379"

    adminer: 
      image: adminer:5.4.2
      container_name: url-shortener-adminer
      ports:
        - "8080:8080"
      depends_on:
        - db

volumes:
  postgres_data:

